Admiral-Piett/goaws

goaws.go, gosqs/gosqs.go
=> Add Mutex Lock on Queues Map for Reads and Read/Write

conf/config.go, conf/config_test.go, conf/goaws.yaml, goaws.go
- Added 2 port congigurating in yaml
- Remove the port option from the command line.
=> Add two port config for yopa and or (fake-sns + fake-sqs) compatibility

README.md
As per https://github.com/p4tin/goaws/issues/71.
=> Fixed the installation instructions in the README

gosns/gosns.go, gosns/gosns_create_message_test.go
=> Add subject to message

README.md
=> Fix TravisCI badge in README.md

app/gosqs/gosqs.go
=> Parse Url Queue the Go Way

app/gosqs/gosqs.go, app/gosqs/message_attributes.go, app/servertest/server_test.go
=> Calculate MD5 checksum of MessageAttributes

app/gosns/gosns.go
- Perform check during Subscribe function to bypass adding
subscription if the Endpoint and TopicArn already exist.
=> SNS - Prevent duplicate subscriptions

app/gosqs/gosqs.go, app/router/router.go, app/sqs.go
The library I'm using requires the DeleteMessageBatch api
=> Add support for DeleteMessageBatch to sqs

app/gosqs/gosqs.go, app/gosqs/message_attributes.go, app/sqs.go, app/sqs_messages.go
This PR adds attributes to the output format of the `ReceiveMessage` action. It also refactors `app/gosqs/sosqs.go` to make it easier to read.
=> add attributes support to ReceiveMessage

app/gosqs/gosqs.go, app/gosqs/gosqs_test.go, app/gosqs/message_attributes.go, app/router/router.go, app/sqs_messages.go
This PR 
* introduces SendMessageBatch functionality. 
* add QueueNamePrefix filter to ListQueues
It closes #141 #74
=> Add SendMessageBatch support and QueueNamePrefix filter to ListQueues

app/gosqs/gosqs.go
=> Fix on a deadlock for ReceiveMessage when wait time is specified

app/gosqs/gosqs.go
=> Unlock SyncQueue before early return

app/gosns/gosns.go
https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html
When an SNS subscription calls its endpoint, Amazon recognizes responses in the range of 200-499 as successful Notification deliveries. Responses outside of that range will trigger the Subscription's retry policy.
This PR updates the `callEndpoint` method to allow this range instead of just response codes divisible by 200.
=> Update permissible SNS endpoint call response codes

app/gosqs/gosqs.go, app/gosqs/gosqs_test.go, app/gosqs/queue_attributes.go, app/gosqs/queue_attributes_test.go, app/sqs.go
Hello! We'd like to contribute our implementation of delayed message delivery with `DelaySeconds`. Thanks for such a great project!
=> honour DelaySeconds queue attribute and SendMessage parameter

Dockerfile, app/conf/config.go, app/conf/config_test.go
We shall finally find the default `goaws.yaml` file no matter where it's located in the file structure.  If you happen to delete it or remove it - it'll still start up, but you'll of course, no find it in that case.
=> Fix default config once and for all

.github/README.md, .github/workflows/pr-tests.yml, .github/workflows/release.yaml, .gitignore, makefile.txt
Hopefully this should help us identify cases where changes can't be built for some reason.
=> Add release testing action

go.mod
=> Retract old versions that are being seen as latest

app/common.go, app/conf/config.go, app/conf/config_test.go, app/conf/mock-data/mock-config.yaml
A rebase of https://github.com/Admiral-Piett/goaws/pull/264/files - changes are from @qhenkart's work
=> Allow for queue specific visibility time out setting

app/gosns/gosns.go, app/gosqs/change_message_visibility.go, app/gosqs/change_message_visibility_test.go, app/gosqs/create_queue_test.go, app/gosqs/delete_message.go, app/gosqs/delete_message_test.go, app/gosqs/gosqs.go, app/gosqs/gosqs_test.go, app/gosqs/list_queues_test.go, app/gosqs/message_attributes.go, app/gosqs/receive_message.go, app/gosqs/receive_message_test.go, app/models/models.go, app/models/responses.go, app/router/router.go, app/router/router_test.go, app/sqs_messages.go, smoke_tests/README.md, smoke_tests/fixtures/requests.go, smoke_tests/sqs_change_message_visibility_test.go, smoke_tests/sqs_delete_message_test.go, smoke_tests/sqs_receive_message_test.go, smoke_tests/sqs_send_message_test.go
- sqs.ReceiveMessage
- sqs.ChangeMessageVisibility
- sqs.DeleteMessage
=> JSON API - sqs.ReceiveMessage, sqs.ChangeMessageVisibility, sqs.DeleteMessage

app/gosqs/change_message_visibility.go, app/gosqs/delete_message.go, app/gosqs/get_queue_attributes.go, app/gosqs/receive_message.go, app/gosqs/send_message.go
Fix the API responses to use prepared constants
=> [aws-json] [not a feature update] Fix misc uniformity
