Admiral-Piett/goaws

- gosns/gosns.go
- gosns/gosns_create_message_test.go
If message structure is not marked as JSON, message string must be used as is for all protocols.
If message structure is marked as JSON, it must have "default" element, and it must be used if no protocol specific message was provided.
> Bugfix: SNS properly uses default message

- .gitignore
- vendor/vendor.json
The sirupsen/logrus dependency is currently used by the project, however
it was missing from vendor.json. It's been now added to the project.
> Add missing 'logrus' dependency to vendor.json

- makefile.txt
The amd64 instruction set is compatible with the vast majority of CPUs.
Let's build amd64 executables rather than arm.
> Fixes #131: Build goaws for amd64 rather than arm

- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
I forgot to check the existence of the queue during the SendMessageBatch request. 😒 With this PR I'm adding that check. 
I also realized that one other check against the EmptyBatchRequest error was missing. I've added that one, too. 
#139 introduced a bug which prevented us from deleting messages due to an incorrect struct referencing. This PR also fixes that issue.
> add queue existence check to SendMessageBatch and some other fixes. 

- README.md
- app/cmd/goaws.go
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/gosqs/queue_attributes.go
- app/gosqs/queue_attributes_test.go
- app/router/router.go
- app/sqs.go
- app/sqs_messages.go
This PR introduces ChangeMessageVisibility endpoint and requeueing logic behind VisibilityTimeout. Mutex locking is becoming too strict, which needs to be improved later on.
I've also added DeadLetter Queue support. 
The PR also includes the changes from #143 and closes #85
> Add ChangeMessageVisibility endpoint and implement VisibilityTimeout logic

- app/gosns/gosns.go
Rename `TimeStamp` Message property to `Timestamp` to be consistent with the associated AWS SNS Message Body property.
> ISSUE-154: Rename Message TimeStamp Property

- README.md
- app/common.go
- app/conf/config.go
- app/conf/config_test.go
- app/conf/goaws.yaml
- app/conf/mock-data/mock-config.yaml
- app/gosns/gosns.go
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/gosqs/queue_attributes.go
- app/gosqs/queue_attributes_test.go
- app/sqs.go
Main features in this PR:
- Implement SQS ReceiveMessageWaitTimeSeconds attribute and obeys it in ReceiveMessage
- Adds support to subscribe to SNS with SQS ARN
- Implement SetQueueAttributes (supports VisibilityTimeout, RedrivePolicy and ReceiveMessageWaitTimeSeconds)
- Allowing to config ReceiveMessageWaitTimeSeconds for queues in config file
- Added RedrivePolicy to GetQueueAttributes
Subscribe supports both URL and ARN endpoints and Publish will work in both cases, but I've changed the subscriptions that are created with config file to use ARN as this is how AWS configure subscriptions.
Made SetQueueAttributes  and CreateQueue to support RedrivePolicy in AWS's format (maxReceiveCount is string) but left the support for passing maxReceiveCount as int anyway.
It closes #140 #145 #30
> Implement SQS ReceiveMessageWaitTimeSeconds attribute and Subscribe to SNS with SQS arn

- app/gosns/gosns.go
Remove the `\n` that was appended to the end of the `Timestamp` SNS Message property.
> Remove newline from SNS Message timestamp

- app/conf/config.go
- app/conf/config_test.go
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/sqs.go
- app/sqs_messages.go
This is backward compatible PR to support FIFO queues. If queue name has `.fifo` suffix it will be treated as FIFO. 
- receive a message from the same groupId will lock it and won't allow other consumers to receive it
- visibility timeout and removing message will unlock group
> FIFO Support

- app/common.go
- app/conf/config.go
- app/conf/config_test.go
- app/conf/goaws.yaml
- app/conf/mock-data/mock-config.yaml
- app/gosqs/gosqs.go
Added ability to set attributes for all queues in config file
QueueAttributeDefaults:           # default attributes for all queues
VisibilityTimeout: 30              # message visibility timeout
ReceiveMessageWaitTimeSeconds: 0   # receive message max wait time
> option for QueueAttributeDefaults in config

- app/gosns/gosns.go
- app/gosns/gosns_test.go
- app/sns.go
- app/sns_test.go
This is a minor improvement of https://github.com/p4tin/goaws/pull/159 which created a functionality that differed from SNS. 
1. DataType is now required for message attributes. This would have led users to create a functional message attribute attachment in the emulator that would have broken on deployed environments
2. The new message attribute helper in the SNS package used a new specific datatype and helper logic that made the helper incompatible with SQS message attributes
3. The filter policy now properly looks for the Data Type with a comment on how to extend the filter policy to provide support other data types that SNS currently supports. For now I have maintained the current functionality of only supporting String based data types. Documentation on that …
> adds message attributes to publish that attach to the sqs attributes on raw

- app/conf/config_test.go
app/conf/config_test.go:103: Errorf format %d
has arg (*filterPolicy)["foo"][0] of wrong type
string
> fix test, Errorf format %d

- Dockerfile
When trying to build, I was getting the "dep missing" error:
```
root# docker build .
Sending build context to Docker daemon  5.458MB
Step 1/12 : FROM golang:alpine as builder
---> 22e024490b47
Step 2/12 : WORKDIR /go/src/github.com/p4tin/goaws
---> Using cache
---> d894e2d78145
Step 3/12 : RUN apk add --update --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ dep git
---> Running in 2892cae3ba78
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
ERROR: unsatisfiable constraints:
dep (missing):
required by: world[dep]
The …
```
> Changed the way we get 'dep' command

- app/gosqs/gosqs.go
There is a bug inside `DeleteMessageBatch` function (issue https://github.com/p4tin/goaws/issues/171):
```
2018/09/21 14:58:01 http: panic serving 172.18.0.1:42200: runtime error: slice bounds out of range
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc00015e0a0)
/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x70d980, 0x9cf310)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/p4tin/goaws/app/gosqs.DeleteMessageBatch(0x7c75e0, 0xc000138620, 0xc000137c00)
/go/src/github.com/p4tin/goaws/app/gosqs/gosqs.go:581 +0x150e
net/http.HandlerFunc.ServeHTTP(0x783760, 0x7c75e0, 0xc000138620, 0xc000137c00)
/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/p4tin/goaws/app/router.actionHandler(0x7c75e0, 0xc000138620, 0xc000137c00) …
```
> Fix 'slice bounds out of range' in DeleteMessageBatch

- app/gosqs/gosqs.go
- app/sqs_messages.go
Sqs receive message does not return Attributes this is to add the attributes to the response
> Adding attributes in received message response

- app/router/router.go
I want to configure the health check for goaws on Docker, but the `/health` path is not working because the `/{account}` path is matching the health check request.
```console
$ curl -vs http://127.0.0.1:4100/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#0)
> GET /health HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Sun, 14 Jul 2019 06:03:14 GMT
< Content-Length: 11
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
Bad Request
```
This PR fixes the registration order of health path to make the health check working.
```console
$ curl -vs http://127.0.0.1:4100/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 …
```
> Fix the health check

- app/common.go
- app/gosns/gosns.go
- app/gosqs/gosqs.go
While working with an overly strict client library, I ran across a minor bug in goaws's ErrorResponse. According to the docs (link below), the `RequestId` element should be a sibling of `Error`, but goaws puts it inside. This patch should fix it. I apologize for not adding any tests, my Go knowledge is a bit too limited for that.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-responses.html
> Move ErrorResponse RequestId out of the Error element

- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
Hi @p4tin,
Hope we can merge the below bug fix, thanks!
Fixes panic at  goaws/app/gosqs/gosqs.go:376. use case `DeleteQueue()` while something is still blocked by `ReceiveMessage()`
Fixes the below panic in `ReceiveMessage`
```[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x12bf1a0]
goroutine 50 [running]:
github.com/sebcante/goaws/app/gosqs.ReceiveMessage(0x13fe060, 0xc000088ac0, 0xc0001ce800)
github.com/sebcante/goaws/app/gosqs/gosqs.go:376 +0x410
net/http.HandlerFunc.ServeHTTP(...)
/Users/seb/ap/bin/gobin/go/src/net/http/server.go:1995
github.com/sebcante/goaws/app/gosqs.TestReceiveMessage_WithConcurrentDeleteQueue.func1(0xc000018b20, 0xc000163c00)
github.com/sebcante/goaws/app/gosqs/gosqs_test.go:1081 +0x344
created by …
```
> Fix panic for concurrent DeleteQueue & ReceiveMessage

- app/gosqs/gosqs.go
Deleted entries should be not found but non-deleted entries should be found.
Found this bug when using with [shoryuken](https://github.com/phstc/shoryuken).
> Fix delete check of DeleteMessageBatch

- app/gosqs/gosqs.go
- app/sqs_messages.go
* Use `DeleteQueueResponse` instead of `DeleteMessageResponse` when deleting queue
> Fix the GoSQS response to DeleteQueue

- app/gosqs/gosqs.go
changed ApproximateFirstReceiveTimestamp and SentTimestamp to be returned in millis as per doco https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
> Fix sqs Receive Attributes to be millis

- app/gosns/gosns.go
- app/gosns/gosns_test.go
* Use the configured account ID instead of `000000000000` in topic ARNs 
* Add support for `RawMessageDelivery` & `FilterPolicy` to the `Subscribe` action
* Add more attributes to `GetSubscriptionAttributes` response to bring in line with the AWS response
If you'd prefer these split out into separate atomic PRs, let me know and I'll resubmit.
> Several minor fixes & enhancements to GoSNS

- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
Without this if the client cancels a waiting ReceiveMessage(), goaws risks to send a subsequent message from queue to a ReceiveMessage() handler that no client listens to and make this message not visible to pickup by other active receivers until WaitTimeSeconds is reached
> gosqs added support to cancel context for sqs ReceiveMessage() 

- app/router/router.go
- app/router/router_test.go
Requests to `SigningCertURL` are currently handled by `actionHandler` instead of `pemHandler` because of wrong routes order. This PR fix this issue.
> fix routes order

- app/common.go
- app/conf/config.go
- app/conf/goaws.yaml
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/sqs.go
[MessageDeduplicationId](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html) support feature.
Any messages sent with the same message deduplication ID are accepted successfully but aren't delivered during the 5-minute deduplication interval.
It works on fifo queues only. For backward compatibility `EnableDuplicates` (`false` by default) added to goaws.yaml file.
> MessageDeduplicationId support

- app/gosns/gosns.go
In situation when subscribe a queue to an SNS topic with `RawMessageDelivery` option set up and we push encoded JSON
```
{\"default\": \"{\\\"test\\\": \\\"xxxx\\\"}\"}
```
The message is forwarded and contains protocol:
```
{
"Messages": [
{
"MessageId": "b6e8402a-2798-405c-9955-78c10061610a",
"ReceiptHandle": "b6e8402a-2798-405c-9955-78c10061610a#cbcbd29e-f9a8-4321-b3b0-3f5631ff1a8b",
"MD5OfBody": "7b2d325f1dac7c79cf89e1fcde3b2e1d",
"Body": "{\"default\": \"{\\\"test\\\": \\\"xxxx\\\"}\"}",
"Attributes": {
"ApproximateFirstReceiveTimestamp": "1601971148229",
"SenderId": "1601971148229",
"ApproximateReceiveCount": "1",
"SentTimestamp": "1601971148229"
},
"MD5OfMessageAttributes": "d41d8cd98f00b204e9800998ecf8427e"
}
]
}
```
AWS in `receive-message` don't show the protocol of message but …
> Fix message decoding

- Dockerfile
- app/common.go
- app/conf/config.go
- app/conf/config_test.go
- app/conf/goaws.yaml
- app/conf/mock-data/mock-config.yaml
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/gosqs/queue_attributes.go
- app/sqs.go
Introduced a queue attribute: `MaximumMessageSize`, which limits the size of the messages accepted by the queue.
Default value is set at 262144 (256K).
Can be configured in `/conf/goaws.yaml`:
```
Local:
QueueAttributeDefaults:
MaximumMessageSize: 1024
```
> Added support for MaximumMessageSize

- app/common.go
- app/conf/config.go
- app/conf/config_test.go
- app/conf/mock-data/mock-config.yaml
Allow to set queue `RedrivePolicy` in `config.yml`
```
- Name: local-queue3                # Queue name
RedrivePolicy: '{"maxReceiveCount": 100, "deadLetterTargetArn":"arn:aws:sqs:us-east-1:000000000000:local-queue3-dlq"}'  
- Name: local-queue3-dlq  
```
> sqs: allow redrive-policy to be set from config yaml

- app/gosns/gosns.go
Mistake in casing breaks library and tests, simply fix the casing.
> Fix broken struct field casing

- app/gosns/gosns.go
- app/gosns/gosns_create_message_test.go
When I published sns message with message attribute, DataType sould be `String` but `StringValue` is returned.
```
$ aws --endpoint-url http://127.0.0.1:4100 sns publish --message test --topic-arn arn:aws:sns:us-east-1:100010001000:local-topic1 --message-attributes '{"test":{"DataType": "String", "StringValue": "test!"}}'
```
```
$ aws --endpoint-url http://127.0.0.1:4100 sqs receive-message --queue-url http://us-east-1.goaws.com:4100/100010001000/local-queue3
{
"Messages": [
{
"MessageId": "fb8a8253-36c6-4a4d-96be-e005f41240a5",
"ReceiptHandle": "fb8a8253-36c6-4a4d-96be-e005f41240a5#1cce6f07-2ffa-4709-97bb-f8dff7584e52",
"MD5OfBody": "99a983d00399afc3712ae7d82d13ca86",
"Body": "{\"Type\":\"Notification\",\"Token\":\"\",\"MessageId\":\"b6cab133-ed2e-44e1-82fd-137e77aeaa7e\",\"TopicArn\":\" …
```
> fix incorrect data type value of message attribute.

- app/sns_messages.go
XML response format is malformed for `list-subscriptions-by-topic`. Turns out the struct was defined but unused.
Reproduced by aws cli version 2.2.13 on macOS
```
aws --endpoint-url http://localhost:4100 --debug sns list-subscriptions-by-topic --topic-arn <topic_arn>
```
> Fix xml response for list-subscriptions-by-topic

- go.mod
- go.sum
Need to upgrade to test SNS:PublishBatch as not available at time of v1.34.0 release
ref https://github.com/Admiral-Piett/goaws/issues/270
so may as well upgrade to latest (v1)
> Upgrade AWS SDK (v1) dep to latest (v1.47.3)

- app/cmd/goaws.go
It would be useful to set a specific log level by providing a string as other levels apart from info and debug are useful.
Have prioritised the existing debug flag for backwards compatibility but would recommend its removal.
> Allow setting any log level

- app/gosns/gosns.go
- app/gosns/gosns_test.go
I added the `Owner` field for both the `ListSubscriptions` and `ListSubscriptionsByTopic` requests, as well as added tests to confirm the field is populated with the expected value in the response.
---
-> `ListSubscriptions`
---
-> `ListSubscriptionsByTopic`
> Note - sorry it took so long to get to this one!! Luckily the changes were pretty straightforward, and the tests are passing smoothly. Let me know if you have any questions 👍
> Include Owner value in Subscriptions and SubscriptionsByTopic responses

- Dockerfile
This change includes a healthcheck in the `Dockerfile` to ensure the container starts in a healthy state before being ready to serve requests. Thanks to issue #258 for the suggestion.
```
cdaly@9:24:52 ‹ docker_healtcheck ● › : ~/GITHome/goaws
[0] % docker run -d 6bb46d55f31b
7587581446d66df072aef7ab5c6ba30b88f14c91ec72cb0c2fa4c7ccc7cf25cd
cdaly@9:25:05 ‹ docker_healtcheck ● › : ~/GITHome/goaws
[0] % docker ps
CONTAINER ID   IMAGE          COMMAND     CREATED        STATUS                           PORTS      NAMES
7587581446d6   6bb46d55f31b   "./goaws"   1 second ago   Up 1 second (health: starting)   4100/tcp   quirky_yalow
cdaly@9:25:07 ‹ docker_healtcheck ● › : ~/GITHome/goaws
[0] % docker ps
CONTAINER ID   IMAGE          COMMAND     CREATED         STATUS …
```
> Include HEALTHCHECK in Docker container

- .goreleaser.yml
While trying to migrate workloads from amd64 to arm64, having a single tag for both architectures makes the transition easier.
References:
- https://goreleaser.com/cookbooks/multi-platform-docker-images/#creating-multi-platform-docker-images-with-goreleaser
- https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/
> chore(release): build multi-arch docker image with same suffix

- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
- app/gosqs/message_attributes.go
- app/gosqs/send_message.go
- app/gosqs/send_message_test.go
- app/models/models.go
- app/models/models_test.go
- app/models/responses.go
- app/router/router.go
- app/router/router_test.go
- app/sqs_messages.go
- smoke_tests/sqs_send_message_test.go
- a. Implement <NewStruct>.SetAttributesFromForm - even if it just returns without doing anything.
- b. You may also need to handle UnmarshalJSON for any nested request attributes/objects.
> [aws-json] Migrate SQS SendMessage

- app/gosns/subscribe.go
- smoke_tests/sns_subscribe_test.go
The actual response value "subscriptionArn" is not a valid arn format.
This bug will affects to the developments on other APIs that use Subscription.
> [aws-json] Fix the invalid format "subscriptionArn" value in Subscribe API response

- app/gosqs/change_message_visibility.go
- app/gosqs/gosqs.go
- app/gosqs/gosqs_test.go
I just noticed you released the JSON API update, congratulations and thanks for your time and effort!
I was trying it out today and everything seems to work as expected, except for DLQ MaxReceiveCounts. As described in #263 in AWS the attribute describes the number of attempts before sending a message to the DLQ, not the number of retries.
There was also a small error when iterating over the messages where when a message that got sent to the DLQ would skip the next message in that queue for the timeout check in that iteration.
Closes: #263
> Send message to DLQ after correct number of attempts

- app/models/requests.go
- app/models/requests_test.go
(This is split change from https://github.com/Admiral-Piett/goaws/pull/339)
Parallel "Publish" request to a single goaws instance will randomly corrupt DataType values like below:
- `S\u0000ring`
- `\u0000\u0000\u0000\u0000\u0000\u0000`
- `Sring\u0000`
- `S\u0000tingg`
We should keep enclosing Caser instance in a request thread.
https://pkg.go.dev/golang.org/x/text@v0.20.0/cases#Caser
> A Caser may be stateful and should therefore not be shared between goroutines.
There is a similar issue with this problem.
https://github.com/golang/go/issues/59520
We faced this problem with our business application but you can reproduce the same issue with the below code.
```
var caser = cases.Title(language.AmericanEnglish)
var dataType = []string{"String", "Binary"}
func TestCaser(t *testing.T) {
for r …
```
> Move caser from a global variable to a local variable

- app/models/requests.go
- app/models/requests_test.go
- smoke_tests/sns_publish_batch_test.go
Factor out attribute parsing for SendMessage, SendMessageBatch, and Publish in the process.
I believe this change is adequately covered by the smoke tests, but am happy to be convinced otherwise
> Implement message attribute parsing for PublishBatch
